export const SET_CHARACTERS = "SET_CHARACTERS";
export const SET_SELECTED_CHARACTER = "SET_SELECTED_CHARACTER";
export const CLEAR_SELECTED_CHARACTER = "CLEAR_SELECTED_CHARACTER";
export const SET_LOADING = "SET_LOADING";
export const SET_SEARCH_TERM = "SET_SEARCH_TERM";
